version: '3.8'

services:
  back-end:
    container_name: 'back-end'
    build:
      context: ./back-end
    volumes:
      - ./back-end:/app/node_modules
      - /app/node_modules
    ports:
      - "3000:3000"

  vue-frontend:
    container_name: 'vue-frontend'
    build:
      context: ./vue-frontend
    volumes:
      - ./vue-frontend:/app/node_modules
      - /app/node_modules
    depends_on:
      - back-end

  nginx:
    container_name: nginx
    build:
      context: ./vue-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - back-end
      - vue-frontend
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  mariadb:
    container_name: mariadb
    restart: always
    image: mariadb:10.6
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./log/mysql:/var/log/mysql
    networks:
      - mysqlnetwork
    environment:
      - MYSQL_ROOT_PASSWORD=1234a
      - MYSQL_DATABASE=local
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=1234a

volumes:
  certbot-etc:
  certbot-var:
  db-data:

networks:
  mysqlnetwork: