name: Deploy to Live Server

on:
  push:
    branches:
      - main
      - domainSsl

jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Live Server
        run: |
          ssh -o StrictHostKeyChecking=no root@13.212.254.201 << 'EOF'
            cd /home/test-project
            docker-compose down
            docker-compose up --build -d
          EOF

  deploy-domainSsl:
    if: github.ref == 'refs/heads/domainSsl'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Live Server
        run: |
          ssh -o StrictHostKeyChecking=no root@13.212.254.201 << 'EOF'
            cd /home/test-project
            docker-compose down
            docker-compose up --build -d
          EOF